patientenstelle/urls.py
from django.contrib import admin
from django.urls import path
from main.views import home, about, offer, contact, membership, news, single_post, membership_form, links, agb, privacy, impressum

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('offer/', offer, name='offer'),
    path('contact/', contact, name='contact'),
    path('membership/', membership, name='membership'),
    path('membership/<slug:slug>', membership_form, name='membership_form' ),
    path('news/', news, name='news'),
    path('news/<int:pk>', single_post, name='single_post'),
    path('links/', links, name='links'),
    path('agb/', agb, name='agb'),
    path('privacy/', privacy, name='privacy'),
    path('impressum/', impressum, name='impressum'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
# Create your models here.

class Page(models.Model):
    PAGE = [
        ('home', 'Home'),
        ('news', 'News'),
        ('offer', 'Angebot'),
        ('about', 'About'),
        ('membership', 'Mitgliedschaft'),
        ('contact', 'Kontakt'),
        ('links', 'Links'),
        ('agb', 'AGB'),
        ('impressum', 'Impressum'),
        ('privacy', 'Datenschutzerklärung'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    page = models.CharField(max_length=10, choices=PAGE, unique=True)

    class Meta:
        verbose_name = "Seite"
        verbose_name_plural = "Seiten"
        
    def __str__(self):
        return self.title 


class Link(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    image = models.ImageField(upload_to='images/')
    description = models.TextField()
    
    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autoren"

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=10, default='#FFFFFF')

    class Meta:
        verbose_name = "Kategorie"
        verbose_name_plural = "Kategorien"

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.PROTECT)
    file = models.FileField(upload_to='files/', blank=True, null=True)
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    lead = models.TextField()
    content = models.TextField(blank=True)
    published = models.BooleanField(default=True)
    img = models.ImageField(upload_to='images/', blank=True, null=True)

    class Meta:
        verbose_name = "Blog Eintrag"
        verbose_name_plural = "Blog Einträge"
        ordering = ['-date']

    def __str__(self):
        return self.title

class TeamMember(models.Model):
    TEAM = [
    ('vorstand', 'Vorstand'),
    ('advice', 'Beratung'),
]
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    image_alt = models.CharField(max_length=100, blank=True, null=True)
    team = models.CharField(max_length=8, choices=TEAM, default='vorstand')

    class Meta:
        verbose_name = "Team Mitglied"
        verbose_name_plural = "Team Mitglieder"

    def __str__(self):
        return self.name


class Offer(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    frontpage = models.BooleanField(default=False)
    order = models.PositiveIntegerField(default=0)

    

    class Meta:
        verbose_name = "Angebot"
        verbose_name_plural = "Angebote"
        ordering = ['order']
    
    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

class ContactForm(forms.Form):
    required_css_class = 'required'
    SALUTATION = [
        ('mr', 'Herr'),
        ('mrs', 'Frau'),
        ('other', 'Andere'),
    ]
    salutation = forms.CharField(label='Anrede', max_length=4, widget=forms.Select(choices=SALUTATION,
                                                                                   attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-main focus:border-main block p-2'}))
    prename = forms.CharField(max_length=100, 
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Vorname'}))
    name = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Nachname'}))
    email = forms.EmailField(max_length=254, required=True,
                             widget=forms.TextInput(attrs={'class': 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-main focus:border-main block w-full p-2.5',
                                                     'placeholder': 'E-Mail'}))
    phone = forms.CharField(label='Telefonnummer', max_length=20, required=False,
                            widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Telefon'}))
    message = forms.CharField(label='Nachricht', required=True,
                            widget=forms.Textarea(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main'}))
    data_policy_accepted = forms.BooleanField(required=True,
                                              widget=forms.CheckboxInput(attrs={'class': 'w-4 h-4 text-primary-600 bg-gray-100 border-gray-300 rounded focus:ring-main dark:focus:ring-primary-600 dark:ring-offset-gray-800 focus:ring-2',
                                                     'placeholder': 'Telefon'}))
    captcha = ReCaptchaField(widget=ReCaptchaV3(), label=False, error_messages={
        'inv': 'reCaptcha-Validierung fehlgeschlagen. Bitte versuche es später noch einmal oder kontaktiere mich via info@cams-world.de, wenn das Problem weiterhin besteht.'
    })

class MembershipForm(forms.Form):
    required_css_class = 'required'
    SALUTATION = [
        ('mr', 'Herr'),
        ('mrs', 'Frau'),
        ('other', 'Andere'),
    ]
    salutation = forms.CharField(label='Anrede', max_length=4, widget=forms.Select(choices=SALUTATION,
                                                                                   attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-main focus:border-main block p-2'}))
    prename = forms.CharField(max_length=100, 
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Vorname'}))
    name = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Nachname'}))
    email = forms.EmailField(max_length=254, required=True,
                             widget=forms.TextInput(attrs={'class': 'shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-main focus:border-main block w-full p-2.5',
                                                     'placeholder': 'E-Mail'}))
    phone = forms.CharField(label='Telefonnummer', max_length=20, required=False,
                            widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Telefon'}))
    street = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Strasse und Hausnummer'}))
    plz = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': '0000'}))
    place = forms.CharField(max_length=100, required=True,
                           widget=forms.TextInput(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main',
                                                     'placeholder': 'Ort'}))
    message = forms.CharField(label='Nachricht', required=False,
                            widget=forms.Textarea(attrs={'class': 'block w-full p-3 text-sm text-gray-900 border border-gray-300 rounded-lg shadow-sm bg-gray-50 focus:ring-main focus:border-main'}))
    data_policy_accepted = forms.BooleanField(required=True,
                                              widget=forms.CheckboxInput(attrs={'class': 'w-4 h-4 text-primary-600 bg-gray-100 border-gray-300 rounded focus:ring-main dark:focus:ring-primary-600 dark:ring-offset-gray-800 focus:ring-2',
                                                     'placeholder': 'Telefon'}))
    captcha = ReCaptchaField(widget=ReCaptchaV3(), label=False, error_messages={
        'inv': 'reCaptcha-Validierung fehlgeschlagen. Bitte versuche es später noch einmal oder kontaktiere mich via info@cams-world.de, wenn das Problem weiterhin besteht.'
   })

main/views.py
from django.shortcuts import render
from .models import Link, TeamMember, Page, BlogPost, Offer
from .forms import ContactForm, MembershipForm
from django. conf import settings
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError

import datetime

# Create your views here.
year = datetime.datetime.now().year

def home(request):
    page = Page.objects.get(page='home')
    offers = Offer.objects.filter(frontpage=True)
    return render(request, 'home.html', {'page': page, 'year': year, 'offers': offers})

def about(request):
    advisors = TeamMember.objects.filter(team='advice')
    vorstand = TeamMember.objects.filter(team='vorstand')
    page = Page.objects.get(page='about')
    return render(request, 'about.html', {'page': page, 'year': year, 'advisors': advisors, 'vorstand': vorstand})

def offer(request):
    page = Page.objects.get(page='offer')
    offers = Offer.objects.all()
    return render(request, 'offer.html', {'page': page, 'year': year, 'offers': offers})

def contact(request):
    page = Page.objects.get(page='contact')
    submitted = False
    email_error = False
    
    form = ContactForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        cd = form.cleaned_data
        subject, from_email = 'Mitgliederanmeldung Patientenstelle', settings.EMAIL_HOST_USER
        data = {
            'salutation': cd['salutation'], 
            'prename': cd['prename'], 
            'name': cd['name'], 
            'email': cd['email'], 
            'phone': cd['phone'], 
            'street': cd['street'], 
            'plz': cd['plz'], 
            'place': cd['place'], 
            'message': cd['message'], 
            'membership': membership
        }

        customer_html_content = render_to_string('email-membership-customer.html', data)
        admin_html_content = render_to_string('email-membership-admin.html', data)
        customer_text_content = render_to_string('email-membership-customer.txt', data)
        admin_text_content = render_to_string('email-membership-admin.txt', data)

        try:
            customer_msg = EmailMultiAlternatives(subject, customer_text_content, from_email, [cd['email']])
            customer_msg.attach_alternative(customer_html_content, "text/html")
            customer_msg.send()

            admin_msg = EmailMultiAlternatives(subject, admin_text_content, from_email, ['patientenstelle.basel@bluewin.ch'])
            admin_msg.attach_alternative(admin_html_content, "text/html")
            admin_msg.send()
        except Exception as e:
            return HttpResponseRedirect('?email_error=True')

        return HttpResponseRedirect('?submitted=True')
    else:
        form = MembershipForm(request.POST or None)
        if 'submitted' in request.GET:
            submitted = True
        elif 'email_error' in request.GET:
            email_error = True

    return render(request, 'contact.html', {'page': page, 'year': year, 'form': form,'submitted': submitted, 'email_error': email_error})

def membership(request):
    page = Page.objects.get(page='membership')
    return render(request, 'membership.html', {'page': page, 'year': year})

def membership_form(request, slug):
    submitted = False
    email_error = False
    page = Page.objects.get(page='membership')
    form = MembershipForm(request.POST or None)
    if slug == 'single':
        membership = 'Anmeldung Einzelmitgliedschaft'
    elif slug == 'patron':
        membership = 'Gönner*in werden'
    elif slug == 'family':
        membership = 'Anmeldung Familienmitgliedschaft'
    if request.method == 'POST' and form.is_valid():
        try:
            cd = form.cleaned_data
            subject, from_email = 'Mitgliederanmeldung Patientenstelle', settings.EMAIL_HOST_USER
            data = {'salutation':cd['salutation'], 'prename': cd['prename'], 'name': cd['name'], 'email':cd['email'], 'phone':cd['phone'], 'street':cd['street'], 'plz':cd['plz'], 'place':cd['place'], 'message':cd['message'], 'membership': membership}
            customer_html_content = render_to_string('email-membership-customer.html', data)
            admin_html_content = render_to_string('email-membership-admin.html', data)
            customer_text_content = render_to_string('email-membership-customer.txt', data)
            admin_text_content = render_to_string('email-membership-admin.txt', data)
            customer_msg = EmailMultiAlternatives(subject, customer_text_content, from_email, [cd['email']])
            customer_msg.attach_alternative(customer_html_content, "text/html")
            customer_msg.send()
            admin_msg = EmailMultiAlternatives(subject, admin_text_content, from_email, ['patientenstelle.basel@bluewin.ch'])
            admin_msg.attach_alternative(admin_html_content, "text/html")
            admin_msg.send()
        except Exception as e:
            return HttpResponseRedirect('?email_error=True')

        return HttpResponseRedirect('?submitted=True')
    else:
        form = MembershipForm(request.POST or None)
        if 'submitted' in request.GET:
            submitted = True
        elif 'email_error' in request.GET:
            email_error = True

    return render(request,'membership-form.html', {'form': form, 'page': page, 'year': year, 'membership': membership, 'submitted': submitted, 'email_error': email_error})

def news(request):
    page = Page.objects.get(page='news')
    posts = BlogPost.objects.filter(published = True).order_by('-date')
    return render(request, 'news.html', {'page': page, 'year': year, 'posts': posts})

def single_post(request, pk):
    post = BlogPost.objects.get(pk=pk)
    page = Page.objects.get(page='news')
    return render(request, 'single-post.html', {'post': post, 'page': page, 'year': year})

def links(request):
    page = Page.objects.get(page='links')
    links = Link.objects.all()
    return render(request, 'links.html', {'page': page, 'year': year, 'links': links})

def agb(request):
    page = Page.objects.get(page='agb')
    return render(request, 'legal.html', {'page': page, 'year': year})

def privacy(request):
    page = Page.objects.get(page='privacy')
    return render(request, 'legal.html', {'page': page, 'year': year})

def impressum(request):
    page = Page.objects.get(page='impressum')
    return render(request, 'legal.html', {'page': page, 'year': year})

main/templates/about.html
{% extends 'page.html' %}


{% block content %}
  <!-- Hero section -->
<div class="relative isolate -z-10 overflow-hidden bg-gradient-to-b from-blue-100/20 pt-14">
    <div class="absolute inset-y-0 right-1/2 -z-10 -mr-96 w-[200%] origin-top-right skew-x-[-30deg] bg-white shadow-xl shadow-blue-600/10 ring-1 ring-blue-50 sm:-mr-80 lg:-mr-96" aria-hidden="true"></div>
    <div class="mx-auto max-w-screen-lg px-6 lg:py-32 lg:px-8">
        <div class="flex gap-20 w-full">
            <div>
                <h1 class="max-w-2xl text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">{{ page.title }}</h1>
                <div class="flex flex-col lg:flex-row mt-6 gap-6">
                    <p class="text-lg leading-8 text-gray-600">{{ page.content }}</p>
                    <div class="flex-shrink-0">
                        <img src="{{ page.image.url }}" alt="" class="h-full rounded-md w-96 object-cover">
                      </div>
                </div>
                
            </div>
            
          </div>
    </div>
    <div class="absolute inset-x-0 bottom-0 -z-10 h-24 bg-gradient-to-t from-white sm:h-32"></div>
</div>

<!--
<div class="absolute -top-80 left-[max(6rem,33%)] -z-10 transform-gpu blur-3xl sm:left-1/2 md:top-20 lg:ml-20 xl:top-3 xl:ml-56" aria-hidden="true">
    <div class="aspect-[801/1036] w-[50.0625rem] bg-gradient-to-tr from-[#2a23f7] to-[#3533a1] opacity-20" style="clip-path: polygon(63.1% 29.6%, 100% 17.2%, 76.7% 3.1%, 48.4% 0.1%, 44.6% 4.8%, 54.5% 25.4%, 59.8% 49.1%, 55.3% 57.9%, 44.5% 57.3%, 27.8% 48%, 35.1% 81.6%, 0% 97.8%, 39.3% 100%, 35.3% 81.5%, 97.2% 52.8%, 63.1% 29.6%)"></div>
</div>
-->
   <!-- Team section -->
<div class="mx-auto mt-12 max-w-screen-lg px-6 sm:mt-12 lg:px-8 pb-32">
    <div class="mx-auto lg:mx-0">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Unser Team</h2>
        <p class="mt-6 text-lg leading-8 text-gray-600">Unser engagiertes Team besteht aus Fachleuten, die Sie kompetent und mit Einfühlungsvermögen beraten.</p>
    </div>
    <div class="border-b border-gray-300 mt-8 pb-2">
        <h3 class="text-xl font-semibold leading-6 text-gray-900">Beratung</h3>
    </div>
    <ul role="list" class="mx-auto mt-20 grid max-w-2xl grid-cols-2 gap-x-8 gap-y-16 text-center lg:mx-0 lg:max-w-none sm:grid-cols-3">
        {% for advisor in advisors %}
        <li>
            {% if advisor.image %}
            <img class="mx-auto h-24 w-24 object-cover rounded-full" src="{{ advisor.image.url }}" alt="Profil Bild von {{ advisor.name }}">
            {% else %}
            <img class="mx-auto h-24 w-24 object-cover rounded-full" src="../../media/defaul-profile.png" alt="default Profil image">
            {% endif %}
            <h3 class="mt-6 text-lg font-semibold leading-8 tracking-tight text-main">{{ advisor.name }}</h3>
            <p class="text-base leading-7 text-gray-600">{{ advisor.position }}</p>
            <p class="text-sm leading-6 text-gray-500">{{ advisor.get_team_display }}</p>
        </li>
        {% endfor %}
    </ul>
    <div class="border-b border-gray-300 mt-8 pb-2">
        <h3 class="text-xl font-semibold leading-6 text-gray-900">Vorstand</h3>
    </div>
    <ul role="list" class="mx-auto mt-20 grid max-w-2xl grid-cols-2 gap-x-8 gap-y-16 text-center lg:mx-0 lg:max-w-none sm:grid-cols-3">
        {% for vorstand_member in vorstand %}
        <li>
            {% if vorstand_member.image %}
            <img class="mx-auto h-24 w-24 object-cover rounded-full" src="{{ vorstand_member.image.url }}" alt="Profil Bild von {{ vorstand_member.name }}">
            {% else %}
            <img class="mx-auto h-24 w-24 object-cover rounded-full" src="../../media/defaul-profile.png" alt="default Profil image">
            {% endif %}
            <h3 class="mt-6 text-lg font-semibold leading-8 tracking-tight text-main">{{ vorstand_member.name }}</h3>
            <p class="text-base leading-7 text-gray-600">{{ vorstand_member.position }}</p>
            <p class="text-sm leading-6 text-gray-500">{{ vorstand_member.get_team_display }}</p>
        </li>
        {% endfor %}
    </ul>
    
</div>

{% endblock %}

main/templates/contact-form.html
<h2>Nachricht Kontaktformular</h2>
<p>Ihr habt folgende Nachricht über das Kontaktformular erhalten:</p>

<div>
    <div>Nachricht von: 
      <p><span>Anrede: </span><span>{{ salutation }}</span></p>
      <p><span>Vorname: </span><span>{{ prename }}</span></p>
      <p><span>Nachname: </span><span>{{ name }}</span></p>
      <p><span>E-mail: </span><span>{{ email }}</span></p>
      <p><span>Telefon: </span><span>{{ phone }}</span></p>
      <p>
        <h3>Nachricht</h3>
        <p>{{ message }}</p>
      </p>
 	</div>
</div>

Automatisch erstellte Email von der Webseite der Patientenstelle.

main/templates/email-membership-admin.html
<h2>Anmeldung zur Mitgliedschaft</h2>
<p>Es ist eine neue Anmeldung für eine Mitgliedschaft eingetroffen.</p>

<div>
  <h3>Zusammenfassung Ihrer Anmeldung</h3>
    <p><span>Mitgliedschaft: </span><span>{{ membership }}</span></p>
    <div>Anmeldung von: 
      <p><span>Anrede: </span><span>{{ salutation }}</span></p>
      <p><span>Vorname: </span><span>{{ prename }}</span></p>
      <p><span>Nachname: </span><span>{{ name }}</span></p>
      <p><span>E-mail: </span><span>{{ email }}</span></p>
      <p><span>Telefon: </span><span>{{ phone }}</span></p>
      <p>
        <h4>Adresse:</h4>
        <span>{{ street }}</span>
        <span>{{ plz }} {{ place }}</span>
    </p>
 	</div>
  {% if message %}
  	<h3>Nachricht</h3>
    <p>{{ message }}</p>
  {% endif %}
</div>

Automatisch erstellte Email von der Webseite der Patientenstelle.

main/templates/email-membership-customer.html
<h2>Anmeldung zur Mitgliedschaft</h2>
<p>Besten Dank für Ihre Anmeldung, Sie erhalten in Kürze Post von uns, mit den wichtigsten 
  Unterlagen und dem Einzahlungsschein für die Mitgliedschaft. 
  Bei Fragen dürfen Sie uns gerne telefonisch zu unseren Büroöffnungszeiten kontaktieren.</p>

  <div>
    <h3>Zusammenfassung Ihrer Anmeldung</h3>
      <p><span>Mitgliedschaft: </span><span>{{ membership }}</span></p>
      <div>Anmeldung von: 
        <p><span>Anrede: </span><span>{{ salutation }}</span></p>
        <p><span>Vorname: </span><span>{{ prename }}</span></p>
        <p><span>Nachname: </span><span>{{ name }}</span></p>
        <p><span>E-mail: </span><span>{{ email }}</span></p>
        <p><span>Telefon: </span><span>{{ phone }}</span></p>
        <p>
          <h4>Adresse:</h4>
          <span>{{ street }}</span>
          <span>{{ plz }} {{ place }}</span>
      </p>
     </div>
    {% if message %}
      <h3>Nachricht</h3>
      <p>{{ message }}</p>
    {% endif %}
  </div>

Freundliche Grüsse

Patientenstelle Basel
Dornacherstrasse 404
4002 Basel
Tel: 061 261 42 41
Mo. - Fr. von 08.00h bis 11.00h
<a href="mailto:patientenstelle.basel@bluewin.ch">patientenstelle.basel@bluewin.ch</a>

main/templates/legal.html
{% extends 'page.html' %}
{% load markdown_extras %}

{% block content %}

<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-screen-lg px-6 lg:px-8">
        <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ page.title }}</h2>
        <div class="content legal">{{ page.content | convert_markdown | safe }}</div>
    </div>
</div>


{% endblock %}

main/templates/links.html
{% extends 'page.html' %}
{% load markdown_extras %}

{% block content %}
<div class="bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-screen-lg px-6 lg:px-8">
    <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ page.title }}</h2>
        
        <div class="mt-8 lg:mt-16 mb-8 space-y-8 md:grid md:grid-cols-2 md:gap-12 md:space-y-0">
            {% for link in links %}
            <div class="flex flex-col items-start">
                <img class="h-16 object-contain" src="{{ link.image.url }}" alt="Logo">
                <h3 class="mt-4 mb-4 text-2xl font-bold dark:text-white">{{ link.name }}</h3>
                <p class="mb-4 text-gray-500 dark:text-gray-400">{{ link.description }}
                    <a href="{{ link.url }}" target="_blank" class="inline-flex items-center font-medium text-main hover:text-main-dark">
                        mehr <span aria-hidden="true">&rarr;</span>
                    </a>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/single-post.html
{% extends 'page.html' %}
{% load markdown_extras %}

{% block content %}
<div class="mx-auto max-w-screen-lg text-base sm:px-6 lg:px-8 leading-7 text-gray-700 mb-32">
    <section class="bg-white">
        <div class="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl {% if post.img %}lg:grid lg:grid-cols-2 {% endif %}lg:py-16 lg:px-6">
            <div class="font-light text-gray-500 sm:text-lg">
                <div class="flex items-center gap-x-4 text-xs">
                    <time datetime="2020-03-16" class="text-gray-500">{{ post.date }}</time>
                    <div class="relative rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">{{ post.category.name }}</div>
                  </div>
                <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{{ post.title }}</h2>
                <p class="mb-4 content">{{ post.content | convert_markdown | safe  }}</p>
            </div>
            {% if post.img %}
            <img class="w-full rounded-lg mt-12 lg:mt-0" src="{{ post.img.url }}" alt="">
            {% endif %}
        </div>
    </section>
</div>
{% endblock %}